name: Build

on:
  push:
    branches: # ignore any tags
      - "**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
    env:
      RUST_BACKTRACE: full
      RUSTFLAGS: ${{ contains(matrix.target, 'msvc') && '-C target-feature=+crt-static' || '' }}
    runs-on: ${{ contains(matrix.target, 'msvc') && 'windows-latest' || 'ubuntu-latest' }}
    steps:
      - name: Cleanup pre-installed tools
        if: runner.os != 'Windows'
        run: |
          # This is a fix for https://github.com/actions/virtual-environments/issues/1918
          shopt -s nullglob
          sudo rm -rf /usr/share/{dotnet,swift,az*,gradle*,*conda} \
            /opt/{ghc,az} \
            /usr/local/share/boost /usr/local/graalvm /usr/local/julia* "$AGENT_TOOLSDIRECTORY"

      - uses: actions/checkout@v4

      - name: Use GNU tar for cache
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo "Adding GNU tar to PATH"
          echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build ${{ matrix.target }}
        if: runner.os != 'Windows'
        run: |
          set -e
          cargo update
          target=${{ matrix.target }}
          cargo build --release --target $target

          bin=target/$target/release/sticker-bot
          FILE=sticker-bot-${GITHUB_SHA::7}-$target.xz
          xz -cv $bin > $FILE
          echo "FILE=$FILE" >> "$GITHUB_ENV"
          echo "BIN_FILE=$bin" >> "$GITHUB_ENV"

      - name: Build ${{ matrix.target }}
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          cargo update
          $target = "${{ matrix.target }}"
          cargo build --release --target $target

          $bin = "target/$target/release/sticker-bot.exe"
          $FILE = "sticker-bot-$($env:GITHUB_SHA.Substring(0,7))-$target.exe.xz"
          7z a -txz $FILE $bin
          Add-Content -Path $env:GITHUB_ENV -Value "FILE=$FILE"
          Add-Content -Path $env:GITHUB_ENV -Value "BIN_FILE=$bin"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}
          path: ${{ env.FILE }}
